### ISSUE TITLE
do not change loadKSdir

### ISSUE THREAD

**Issue by bendichter** [ben-dichter-consulting/spikes#3]
Instead of changing `loadKSdir`, could you create a new function, `loadNWB`, which takes as an arg the NWB file and (if needed) the .mat file, and outputs the `spikeStruct` object?

**Comment by bendichter** [comment]
loadKSdir_legacy should be renamed back to loadKSdir

**Comment by IvanSmal** [comment]
renamed loadKSdir to loadNWBdir and loadKSdir_legacy to loadKSdir.
